aws/sts.go, aws/sts_mock.go, aws/sts_test.go
This is necessary for a future aws-okta PR that gets the user's username from their caller identity (rather than an IAM user username).
=> Add function for sts get-caller-identity

oidc_cli/cache/cache.go, oidc_cli/cache/cache_test.go, oidc_cli/token_getter.go
Instead of acquiring an exclusive lock on each invocation of oidc clients, we only do it when we need to refresh tokens. This significantly speeds up code that doesn't efficiently re-use session/credentials (such as terraform).
=> [feature] Improve oidc pid locking

oidc_cli/cache/cache.go, oidc_cli/cache/cache_test.go, oidc_cli/client/client.go
Also added some more debug statements and did a bit of refactoring to clear dead code.
2 Issues:
- we were always returning a nil token from the cache when expired (instead of returning the refresh token). we instead return the token and defer checking token validity to the cache layer.
- we don't pass the access token to the refresh flow, instead just send over the refresh token.
=> [fix] Fix OIDC client refresh flow

lambda/Makefile, lambda/eks_s3/cloudwatch_eks_to_s3.go, lambda/eks_s3/cloudwatch_eks_to_s3_test.go
lamba transformation function for records placed into kinesis from cloudwatch. This function process only EKS Logs and drops all other logs.
This has been tested by verifying cloudwatch EKS logs getting stored into S3 after successful lambda processing.
=> [feature] Add lambda to process eks logs from cloudwatch

aws/mocks/ec2.go, go.mod, go.sum
When I ran `make generate-mocks`, I saw new functions from the ec2 api, so I'm adding them here!
=> add missing functions to ec2 mock

tftest/test.go
For some terraform tests we want to skip the destroy process and let our
garbage collection processes deal with it.
=> tftest: skip destroy

tftest/util.go
If our standard variables (project, env, service, owner) are not set,
set them.
=> tftest: include standard vars automatically

lambda/tfe-metrics/runner/runner.go
If the admin api run object was nil, this would panic.
=> [fix] panic in tfe-metrics

oidc_cli/client/client.go, oidc_cli/client/config_options.go
Allow oidc to specify the auth server's authstyle (instead of always reverting to autodiscover) to save on requests issued.
=> feature: oidc_cli: Allow specifying oauth2 AuthStyle

keypair/keypair.go, keypair/keypair_test.go, snowflake/connect_test.go
In another PR, I had trouble with updating RSA_PUBLIC_KEY_2 due to an invalid public key type. I think this will help because [this link](https://community.snowflake.com/s/article/How-to-verify-the-Public-Private-Key-Connectivity-using-SnowSQL) seems to have pk8 flags turned on.
```
a)   Unencrypted version
To generate an unencrypted version of private key, use the following command:
$ openssl genrsa 2048 | openssl pkcs8 -topk8 -inform PEM -out rsa_key.p8 -nocrypt
To generate an unencrypted version of public key, use the following command:
$ openssl rsa -in rsa_key.p8 -pubout -out rsa_key.pub
```
=> [fix] convert keypair marshaling to pkcs8 because snowflake suggests it

.github/workflows/codeql-analysis.yml
[This build](https://github.com/chanzuckerberg/go-misc/pull/174/checks?check_run_id=2238808342) showed this warning:
```
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. 
Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
```
=> [fix] delete unnecessary codeQL step

lambda/rotator-snowflake/setup/snowflake/snowflake.go, snowflake/connect.go, snowflake/connect_test.go
so I get to call snowflake.Config rather than snowflake.SnowflakeConfig
=> [fix] rename snowflake config to reduce redundancy

snowflake/db.go
This PR changes the configured logger to logrus so it carries over the debugging information from the logrus processing chain that might be used by users of this library. For example, if a user of this library turns off debug logs, the logs from the database tracing won't be logged for that user.
=> fix[logger]: changing logger to logrus 

oidc_cli/storage/storage.go, oidc_cli/token_getter.go
getStorage and getFileStorage were previously located in token_getter.go, but moving them here makes it easier to use the same storage for non token_getting purposes.
=> Move storage functions to storage module

.github/workflows/aws-mocks.yml, .github/workflows/ci.yml, go.mod, go.sum, oidc_cli/client/client.go, oidc_cli/client/server.go, oidc_cli/storage/keyring.go
There seems to be a race condition on WSL2 boxes where the server hangs because the channel is unbufffered and the consumer not consuming. Make these buffered channels.
=> fix: Add buffered channels for OIDC flow

.github/actions/find-changed-packages/action.yml, oidc_cli/oidc_impl/cache/cache.go, oidc_cli/oidc_impl/cache/cache_test.go
Updates module to use gzip compression for tokens stored in cache to allow for larger tokens to be stored. Tokens are compressed prior to writing to the cache and decompressed after reading from the cache.
=> feat: compress token before storing in cache to allow for larger tokens to be cached

oidc_cli/oidc_impl/cache/cache.go
We can make use of the `MarshalOptNoRefresh` function to remove the refreshToken in case keyring returns saying it is too big to set. We are comparing the exact string right now but we want to upgrade the keyring package to have the exact error type `ErrSetDataTooBig` (https://github.com/zalando/go-keyring/blob/master/keyring.go#L17).
=> feat: Remove refresh token if token is too big

oidc_cli/go.mod, oidc_cli/go.sum, oidc_cli/oidc_impl/cache/cache.go
We previously pinned go-keyring because it was truncating passwords, but it is now fixed in the latest version. We need the latest version to use a new Error type.
References:
https://github.com/zalando/go-keyring/pull/86
https://github.com/zalando/go-keyring/issues/80
https://github.com/chanzuckerberg/aws-oidc/issues/359
=> feat: Upgrade keyring package to latest

.github/workflows/ci.yml, .github/workflows/conventional-commits.yml, .github/workflows/mod-update.yml, .github/workflows/release-please.yml
https://czi.atlassian.net/browse/CCIE-3911
This PR updates 'runs-on' in GitHub Actions workflow files to use direct values instead of label arrays.
=> fix: Update runs-on labels in GitHub Actions workflows

config/config.go, config/config_test.go, config/go.mod, config/go.sum, config/testData/alternate_base_name/something.yaml, config/testData/basic/anotherconfig.yaml
I will use this in argus to load a new file like:
`app-config.version.yaml`:
```
api:
version: 0.55.0
```
and then make release-please update `api.version` in that file whenever it runs.
This allows us to still use release-please to keep the version in sync without messing up the main `app-config.yaml`
=> feat: allow adding arbitrary yaml config files

config/go.mod, release-please-config.json
The suffix needs to match the git release major version which is v3 here https://github.com/chanzuckerberg/go-misc/pull/1099/files
=> chore: config should be v3
